spring:
  application:
    name: atomscat-provider
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.1.12
    password: admin123456
    database: 2
    port: 6379

dubbo:
  registry:
    address: zookeeper://192.168.1.12:2181
  consumer:
    check: false

elastic-job:
  servers: 192.168.1.12:2181
  namespace: atomscat_elastic_job