spring:
  application:
    name: atomscat-provider

nacos:
  config:
    server-addr: 192.168.1.14:8848
    namespace: 5f5afe75-b943-40dc-ae5a-6f3e9ab24cf8
    bootstrap:
      enable: true
    data-id: atomscat-provider.yaml
    type: yaml
    ext-config:
      - data-id: elastic-job
        group: servers
        type: yaml
      - data-id: dubbo
        group: provider
        type: yaml